version: '3.9'

services:
  app:
    build:
      context: .
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
      - ./data/web:/vol/web
    environment:
      - SECRET_KEY=devsecretkey
      - DEBUG=1
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASS=changeme
      - EMAIL_USER=mrk191198@gmail.com
      - EMAIL_PASS=gnwtqhxhzfkzqqdb
      - AWS_ACCESS_KEY_ID=AKIAXQ35CJ5DM2R5K5ZK
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_STORAGE_BUCKET_NAME=mrk-django-docker-app
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=changeme